### ISSUE TITLE
[Add Map] CO-OP VS 3 US Generals Challenge

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/ZeroHourWorld#269]
### Map Name

CO-OP VS 3 US Generals Challenge

### Map Kind

Cooperative Mission

### Author

[Dun淼咕]

### Author Contact

(https://www.moddb.com/members/sxandun)

### Download Link

https://www.moddb.com/games/cc-generals-zero-hour/addons/co-op-vs-3-us-generals-challengespecial-edition

**Comment by MahBoiDeveloper** [comment]
Duplicate of #2
